### ISSUE TITLE
Monitoring (Phase 1)

### ISSUE THREAD

**Issue by andressrg** [andressrg/insmed#6]
## TODO
- [x] read the UART characteristic from the HM 10 BLE module [spec](http://www.martyncurrey.com/hm-10-bluetooth-4ble-modules/#HM-10_Services_and_Characteristics) (https://github.com/andressrg/insmed/pull/9)
- [x] parse the Pressure frame sent by the Arduino
- [x] plot the pressure

**Comment by elpablete** [comment]
Do you have a pressure frame example?

**Comment by andressrg** [comment]
We are going to start with a simple ascii one :)

`t<ms-from-arduino-start>p<pressure float>;`

So for example we could have:

`t2831p10.2;t3131p12.2;t3531p14.2;`

for the t part we will be receiving the result of calling [mills()](https://www.arduino.cc/reference/en/language/functions/time/millis/) which is an unsigned long

for the p part we will be receiving a float

**Comment by andressrg** [comment]
Everything here is ready :)
